# This is a basic workflow to help you get started with Actions

name: Deployment

on:
    release:
        types: [published]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Ballerina Build
              uses: ballerina-platform/ballerina-action@2201.0.0
              with:
                  args:
                      pack ./cosmosdb
              env:
                  BASE_URL: ${{ secrets.BASE_URL }}
                  MASTER_OR_RESOURCE_TOKEN: ${{ secrets.MASTER_OR_RESOURCE_TOKEN }}
            - name: Ballerina Push
              uses: ballerina-platform/ballerina-action@2201.0.0
              with:
                  args:
                      push 
              env:
                  WORKING_DIR: ./cosmosdb
                  BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_ACCESS_TOKEN }}
